In [2]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import edhec_risk_kit as erk
from scipy.optimize import minimize

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
hfi = erk.get_hfi_returns()
er = erk.annualize_rets(hfi["2000":], 12)
cov = hfi["2000":].cov()

In [5]:
# Q1 - Monthly parametric guassian VaR at the 1% level
# of the distressed Securiteis strategy?
(erk.var_gaussian(hfi["2000":]["Distressed Securities"], level=1)*100).round(2)

3.14

In [6]:
# Q2 - What was the 1% VaR for the same strategy after applying the Cornish-Fisher Adjustment?

(erk.var_gaussian(hfi["2000":]["Distressed Securities"], level=1, modified=True)*100).round(2)

4.97

In [7]:
# Q3 -  What was the Monthly Historic VaR at the 1% level (as a +ve number) 
# of the Distressed Securities strategy?

(erk.var_historic(hfi["2000":]["Distressed Securities"], level=1)*100).round(2)

4.26

In [10]:
# Q4 - What is the weight of Steel in the EW Portfolio? 

ind = erk.get_ind_returns()
er = erk.annualize_rets(ind["2013":"2017"], 12)
cov = ind["2013":"2017"].cov()

# Portfolio:
l = ['Books', 'Steel', 'Oil', 'Mines']
rf = 0.1 #risk free rate

# Portfolio correspond simply to an allocation of capital
# The weights correspond to the allocation
weights = np.repeat(1/len(l), len(l))
weights[1] * 100

25.0

In [13]:
# Q5 Question 5
# What is the weight of the largest component of the MSR portfolio? 
weights_msr = erk.msr(rf, er[l], cov.loc[l,l])
(weights_msr.max()*100).round(2)

100.0

In [19]:
# Q6 Which of the 4 components has the largest weight in the MSR portfolio?

l[weights_msr.argmax()]

'Steel'

In [20]:
# Q7 - How many of the components of the MSR portfolio have non-zero weights?  

(weights_msr*100).round(2)

array([  0., 100.,   0.,   0.])

In [21]:
# Q8 - 

weights_gmv = erk.gmv(cov.loc[l,l])
(weights_gmv.max()*100).round(2)

47.7

In [22]:
# Q9
l[weights_gmv.argmax()]

'Books'

In [23]:
# Q10
(weights_gmv*100).round(2)

array([47.7 ,  0.  , 43.41,  8.89])

In [24]:
# Q11
weights_msr

array([4.51375048e-15, 1.00000000e+00, 1.40512602e-16, 0.00000000e+00])

In [26]:
weights_gmv

array([4.77024870e-01, 4.33680869e-19, 4.34112024e-01, 8.88631053e-02])

In [32]:
cov =  ind["2018"].cov()
r = ind.loc["2018"]

In [34]:
vol_msr = erk.portfolio_vol(weights_msr, cov.loc[l,l]) * np.sqrt(12)
(vol_msr*100).round(2)

21.98

In [36]:
# Q12

vol_gmv = erk.portfolio_vol(weights_gmv, cov.loc[l, l]) * np.sqrt(12)
(vol_gmv * 100).round(2)

18.97

In [37]:
a = np.random.randn(2, 3) # 
a.shape
b = np.random.randn(2, 1)
c = a + b

In [38]:
c

array([[-1.21459538, -1.75775362, -1.56991031],
       [ 0.40319433, -0.85884689, -1.68815787]])

In [39]:
a

array([[-0.82349576, -1.366654  , -1.17881069],
       [ 0.11595742, -1.1460838 , -1.97539477]])

In [40]:
b

array([[-0.39109962],
       [ 0.2872369 ]])